package com.example.torder.vo;

import com.cetccity.common.base.vo.BaseVo;

/**
 * @program: torder
 * @description: 类别
 * @author: huangjiali 黄嘉丽
 * @create: 2020-03-26 14:22
 **/
public class CategoryVo extends BaseVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.c_code
     *
     * @mbg.generated
     */
    private String cCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.c_parent
     *
     * @mbg.generated
     */
    private String cParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.c_code
     *
     * @return the value of category_info.c_code
     *
     * @mbg.generated
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.c_code
     *
     * @param cCode the value for category_info.c_code
     *
     * @mbg.generated
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.c_name
     *
     * @return the value of category_info.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.c_name
     *
     * @param cName the value for category_info.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.c_parent
     *
     * @return the value of category_info.c_parent
     *
     * @mbg.generated
     */
    public String getcParent() {
        return cParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.c_parent
     *
     * @param cParent the value for category_info.c_parent
     *
     * @mbg.generated
     */
    public void setcParent(String cParent) {
        this.cParent = cParent == null ? null : cParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cCode=").append(cCode);
        sb.append(", cName=").append(cName);
        sb.append(", cParent=").append(cParent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
