package com.example.torder.vo;

import com.cetccity.common.base.vo.BaseVo;

import java.io.Serializable;
import java.util.Date;

/**
 * @program: torder
 * @description: 关注
 * @author: huangjiali 黄嘉丽
 * @create: 2019-12-25 14:09
 **/
public class FavoritesVo extends BaseVo implements Serializable {
    private String code;
    /**
     * Database Column Remarks:
     *   关注ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_info.fav_id
     *
     * @mbg.generated
     */
    private Integer favId;

    /**
     * Database Column Remarks:
     *   关注者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   关注类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_info.fav_type
     *
     * @mbg.generated
     */
    private Integer favType;

    /**
     * Database Column Remarks:
     *   关注对象ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_info.target_id
     *
     * @mbg.generated
     */
    private Integer targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_info.opr
     *
     * @mbg.generated
     */
    private Integer opr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_info.opr_time
     *
     * @mbg.generated
     */
    private Date oprTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table favorites_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_info.fav_id
     *
     * @return the value of favorites_info.fav_id
     *
     * @mbg.generated
     */
    public Integer getFavId() {
        return favId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_info.fav_id
     *
     * @param favId the value for favorites_info.fav_id
     *
     * @mbg.generated
     */
    public void setFavId(Integer favId) {
        this.favId = favId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_info.user_id
     *
     * @return the value of favorites_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_info.user_id
     *
     * @param userId the value for favorites_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_info.fav_type
     *
     * @return the value of favorites_info.fav_type
     *
     * @mbg.generated
     */
    public Integer getFavType() {
        return favType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_info.fav_type
     *
     * @param favType the value for favorites_info.fav_type
     *
     * @mbg.generated
     */
    public void setFavType(Integer favType) {
        this.favType = favType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_info.target_id
     *
     * @return the value of favorites_info.target_id
     *
     * @mbg.generated
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_info.target_id
     *
     * @param targetId the value for favorites_info.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_info.opr
     *
     * @return the value of favorites_info.opr
     *
     * @mbg.generated
     */
    public Integer getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_info.opr
     *
     * @param opr the value for favorites_info.opr
     *
     * @mbg.generated
     */
    public void setOpr(Integer opr) {
        this.opr = opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_info.opr_time
     *
     * @return the value of favorites_info.opr_time
     *
     * @mbg.generated
     */
    public Date getOprTime() {
        return oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_info.opr_time
     *
     * @param oprTime the value for favorites_info.opr_time
     *
     * @mbg.generated
     */
    public void setOprTime(Date oprTime) {
        this.oprTime = oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", favId=").append(favId);
        sb.append(", userId=").append(userId);
        sb.append(", favType=").append(favType);
        sb.append(", targetId=").append(targetId);
        sb.append(", opr=").append(opr);
        sb.append(", oprTime=").append(oprTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}
