package com.example.torder.vo;

import com.cetccity.common.base.vo.BaseVo;

import java.io.Serializable;
import java.util.Date;

/**
 * @program: torder
 * @description: 权限
 * @author: huangjiali 黄嘉丽
 * @create: 2019-12-25 14:14
 **/
public class RightVo extends BaseVo implements Serializable {
    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_info.right_id
     *
     * @mbg.generated
     */
    private Integer rightId;

    /**
     * Database Column Remarks:
     *   权限父级ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_info.right_parent_id
     *
     * @mbg.generated
     */
    private Integer rightParentId;

    /**
     * Database Column Remarks:
     *   权限名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_info.right_name
     *
     * @mbg.generated
     */
    private String rightName;

    /**
     * Database Column Remarks:
     *   权限路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_info.right_url
     *
     * @mbg.generated
     */
    private String rightUrl;

    /**
     * Database Column Remarks:
     *   权限备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_info.right_des
     *
     * @mbg.generated
     */
    private String rightDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_info.opr
     *
     * @mbg.generated
     */
    private String opr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_info.oprtime
     *
     * @mbg.generated
     */
    private Date oprtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table right_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_info.right_id
     *
     * @return the value of right_info.right_id
     *
     * @mbg.generated
     */
    public Integer getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_info.right_id
     *
     * @param rightId the value for right_info.right_id
     *
     * @mbg.generated
     */
    public void setRightId(Integer rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_info.right_parent_id
     *
     * @return the value of right_info.right_parent_id
     *
     * @mbg.generated
     */
    public Integer getRightParentId() {
        return rightParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_info.right_parent_id
     *
     * @param rightParentId the value for right_info.right_parent_id
     *
     * @mbg.generated
     */
    public void setRightParentId(Integer rightParentId) {
        this.rightParentId = rightParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_info.right_name
     *
     * @return the value of right_info.right_name
     *
     * @mbg.generated
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_info.right_name
     *
     * @param rightName the value for right_info.right_name
     *
     * @mbg.generated
     */
    public void setRightName(String rightName) {
        this.rightName = rightName == null ? null : rightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_info.right_url
     *
     * @return the value of right_info.right_url
     *
     * @mbg.generated
     */
    public String getRightUrl() {
        return rightUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_info.right_url
     *
     * @param rightUrl the value for right_info.right_url
     *
     * @mbg.generated
     */
    public void setRightUrl(String rightUrl) {
        this.rightUrl = rightUrl == null ? null : rightUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_info.right_des
     *
     * @return the value of right_info.right_des
     *
     * @mbg.generated
     */
    public String getRightDes() {
        return rightDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_info.right_des
     *
     * @param rightDes the value for right_info.right_des
     *
     * @mbg.generated
     */
    public void setRightDes(String rightDes) {
        this.rightDes = rightDes == null ? null : rightDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_info.opr
     *
     * @return the value of right_info.opr
     *
     * @mbg.generated
     */
    public String getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_info.opr
     *
     * @param opr the value for right_info.opr
     *
     * @mbg.generated
     */
    public void setOpr(String opr) {
        this.opr = opr == null ? null : opr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_info.oprtime
     *
     * @return the value of right_info.oprtime
     *
     * @mbg.generated
     */
    public Date getOprtime() {
        return oprtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_info.oprtime
     *
     * @param oprtime the value for right_info.oprtime
     *
     * @mbg.generated
     */
    public void setOprtime(Date oprtime) {
        this.oprtime = oprtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rightId=").append(rightId);
        sb.append(", rightParentId=").append(rightParentId);
        sb.append(", rightName=").append(rightName);
        sb.append(", rightUrl=").append(rightUrl);
        sb.append(", rightDes=").append(rightDes);
        sb.append(", opr=").append(opr);
        sb.append(", oprtime=").append(oprtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
