package com.example.torder.vo;

import com.cetccity.common.base.vo.BaseVo;

import java.io.Serializable;
import java.util.Date;

/**
 * @program: torder
 * @description: 角色
 * @author: huangjiali 黄嘉丽
 * @create: 2019-12-25 14:15
 **/
public class RoleVo extends BaseVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   角色备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role_des
     *
     * @mbg.generated
     */
    private String roleDes;

    /**
     * Database Column Remarks:
     *   角色父级ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role_parent_id
     *
     * @mbg.generated
     */
    private Integer roleParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.opr
     *
     * @mbg.generated
     */
    private String opr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.oprtime
     *
     * @mbg.generated
     */
    private Date oprtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role_id
     *
     * @return the value of role_info.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role_id
     *
     * @param roleId the value for role_info.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role_name
     *
     * @return the value of role_info.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role_name
     *
     * @param roleName the value for role_info.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role_des
     *
     * @return the value of role_info.role_des
     *
     * @mbg.generated
     */
    public String getRoleDes() {
        return roleDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role_des
     *
     * @param roleDes the value for role_info.role_des
     *
     * @mbg.generated
     */
    public void setRoleDes(String roleDes) {
        this.roleDes = roleDes == null ? null : roleDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role_parent_id
     *
     * @return the value of role_info.role_parent_id
     *
     * @mbg.generated
     */
    public Integer getRoleParentId() {
        return roleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role_parent_id
     *
     * @param roleParentId the value for role_info.role_parent_id
     *
     * @mbg.generated
     */
    public void setRoleParentId(Integer roleParentId) {
        this.roleParentId = roleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.opr
     *
     * @return the value of role_info.opr
     *
     * @mbg.generated
     */
    public String getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.opr
     *
     * @param opr the value for role_info.opr
     *
     * @mbg.generated
     */
    public void setOpr(String opr) {
        this.opr = opr == null ? null : opr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.oprtime
     *
     * @return the value of role_info.oprtime
     *
     * @mbg.generated
     */
    public Date getOprtime() {
        return oprtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.oprtime
     *
     * @param oprtime the value for role_info.oprtime
     *
     * @mbg.generated
     */
    public void setOprtime(Date oprtime) {
        this.oprtime = oprtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleDes=").append(roleDes);
        sb.append(", roleParentId=").append(roleParentId);
        sb.append(", opr=").append(opr);
        sb.append(", oprtime=").append(oprtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
