package com.example.torder.mapper;

import com.example.torder.domain.Advertising;

public interface AdvertisingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    int insert(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    int insertSelective(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    Advertising selectByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Advertising record);
}