package com.example.torder.mapper;

import com.example.torder.domain.Category;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int insertSelective(Category record);

    List findCategoryParentList();
    List findCategoryChildrenList(String cParent);
}