package com.example.torder.mapper;

import com.example.torder.domain.Dics;
import com.example.torder.vo.AdvertisingVo;
import com.example.torder.vo.DicsVo;

import java.util.List;

public interface DicsMapper {
    List findList(DicsVo obj);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dics_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dicsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dics_info
     *
     * @mbg.generated
     */
    int insert(Dics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dics_info
     *
     * @mbg.generated
     */
    int insertSelective(Dics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dics_info
     *
     * @mbg.generated
     */
    Dics selectByPrimaryKey(Integer dicsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dics_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dics_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dics record);
}