package com.example.torder.mapper;

import com.example.torder.domain.Msg;
import com.example.torder.vo.MsgVo;

import java.util.List;

public interface MsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated
     */
    List findMsgList(MsgVo obj);
    int deleteByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated
     */
    int insert(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated
     */
    int insertSelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated
     */
    MsgVo selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Msg record);
}