package com.example.torder.mapper;

import com.example.torder.domain.QA;
import com.example.torder.vo.QAVo;
import com.example.torder.vo.RightVo;

import java.util.List;

public interface QAMapper {
    List findList(QAVo obj);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbg.generated
     */
    int insert(QA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbg.generated
     */
    int insertSelective(QA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbg.generated
     */
    QAVo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QA record);
}