package com.example.torder.mapper;

import com.example.torder.domain.Right;
import com.example.torder.vo.AdvertisingVo;
import com.example.torder.vo.RightVo;

import java.util.List;

public interface RightMapper {
    List findList(RightVo obj);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_info
     *
     * @mbg.generated
     */
    int insert(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_info
     *
     * @mbg.generated
     */
    int insertSelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_info
     *
     * @mbg.generated
     */
    Right selectByPrimaryKey(Integer rightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Right record);
}