package com.example.torder.mapper;

import com.example.torder.domain.RoleRight;
import com.example.torder.vo.RoleRightVo;

import java.util.List;

public interface RoleRightMapper {
    /**
     * 获取列表
     * @param roleRightVo
     * @return
     */
    List findRRList(RoleRightVo roleRightVo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right
     *
     * @mbg.generated
     */
    /**
     * 删除
     * @param rrId
     * @return
     */
    int deleteByPrimaryKey(Integer rrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right
     *
     * @mbg.generated
     */
    int insert(RoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right
     *
     * @mbg.generated
     */
    /**
     * 插入
     * @param record
     * @return
     */
    int insertSelective(RoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right
     *
     * @mbg.generated
     */
    /**
     * 查询
     * @param rrId
     * @return
     */
    RoleRightVo selectByPrimaryKey(Integer rrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right
     *
     * @mbg.generated
     */
    /**
     * 更新
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(RoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleRight record);
}