package com.example.torder.mapper;

import com.example.torder.domain.Talents;

public interface TalentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talents_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer talentsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talents_info
     *
     * @mbg.generated
     */
    int insert(Talents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talents_info
     *
     * @mbg.generated
     */
    int insertSelective(Talents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talents_info
     *
     * @mbg.generated
     */
    Talents selectByPrimaryKey(Integer talentsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talents_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Talents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talents_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Talents record);
}