# Server settings
server:
    port: 12031
    address: 172.16.20.111

# SPRING PROFILES
spring: 
    # APP (for Eureka)
    application:
        name: torderService # 注册到eureka.instance.*
    # DATASOURCE
    datasource: 
        url: jdbc:mysql://localhost:3306/bs?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&nullCatalogMeansCurrent=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
#        druid.initial-size: 1
#        druid.min-idle: 1
#        druid.max-active: 20
#        druid.test-on-borrow: true
#        druid.stat-view-servlet.allow: true

    #activiti
    activiti:
        check-process-definitions: false
        database-schema-update: true
        history-level: full
        db-history-used: true
    # HTTP ENCODING
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jackson:
        #date-format: yyyy-MM-dd'T'HH:mm:ss+0800
        date-format: yyyy-MM-dd HH:mm:ss
        #date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        serialization: 
            write-dates-as-timestamps: false
    #servlet:
        #multipart:
            #max-file-size: 50MB
            #max-request-size: 50MB
    #devtools: 
        #restart: 
            #additional-paths: src\\main\\java\\com\\cetccity\\common\\system\\mgr\\com.cetccity.coc.qzemer.mapper
    thymeleaf: 
        cache: false

# Management
management:
    security:
        enabled: false

# MyBatis
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    typeAliasesPackage: com.example.torder.domain
    mapperLocations: classpath:/com/example/torder/mapper/*.xml
    #configLocation: classpath:/config/mybatis-config.xml

# MyBatis PageHelper.
pagehelper: 
    #autoRuntimeDialect: true #动态数据源时，才设置
    #closeConn: true #动态数据源时，才设置（根据数据库特性设置）
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    pageSizeZero: true
    reasonable: true
    supportMethodsArguments: true
    #params: pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero

# LOGGING
logging:
    level:
        ROOT: info
        org.springframework.web: ERROR
      #  com.ibatis: debug
        com:
            example:
                torder:
        com.example.torder.mapper: debug
        com.example: info
    pattern: 
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    #file: ./logs/${spring.application.name}-${server.address}.log

# Eureka
eureka:
    instance:
        preferIpAddress: true
        #前缀：http://${server.address}/${server.port}
        statusPageUrlPath: /application/info
        healthCheckUrlPath: /application/health
        #statusPageUrlPath: ${management.context-path}/info
        #healthCheckUrlPath: ${management.context-path}/health
        #nonSecurePortEnabled: false
        #securePortEnabled: true
        hostname: ${server.address} #hostName: ${server.address}:${server.port}
        #statusPageUrl: https://${eureka.hostname}/info
        #healthCheckUrl: https://${eureka.hostname}/health
        #homePageUrl: https://${eureka.hostname}/
        #lease-renewal-interval-in-seconds: 10  # 续约更新时间间隔（默认30秒）
        #lease-expiration-duration-in-seconds: 30 # 续约到期时间（默认90秒）
        #metadataMap:
        #    zone: zone-china-fujian
    client:
        serviceUrl:
            defaultZone: http://hostname:12031/eureka/
#            defaultZone: http://localhost:7011/eureka/
        #preferSameZoneEureka: true
        #healthcheck: 
            #enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
        register-with-eureka: false
        fetch-registry: false
