package com.example.torder.domain;

import com.cetccity.common.base.com.cetccity.torder.domain.BasePo;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table advertising_info
 */
public class Advertising extends BasePo implements Serializable {
    /**
     * Database Column Remarks:
     *   广告ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_id
     *
     * @mbg.generated
     */
    private Integer adId;

    /**
     * Database Column Remarks:
     *   广告标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_title
     *
     * @mbg.generated
     */
    private String adTitle;

    /**
     * Database Column Remarks:
     *   广告链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_url
     *
     * @mbg.generated
     */
    private String adUrl;

    /**
     * Database Column Remarks:
     *   广告开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_start
     *
     * @mbg.generated
     */
    private String adStart;

    /**
     * Database Column Remarks:
     *   广告结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_end
     *
     * @mbg.generated
     */
    private String adEnd;

    /**
     * Database Column Remarks:
     *   排序码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_sort
     *
     * @mbg.generated
     */
    private String adSort;

    /**
     * Database Column Remarks:
     *   点击量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_click
     *
     * @mbg.generated
     */
    private String adClick;

    /**
     * Database Column Remarks:
     *   广告类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_type
     *
     * @mbg.generated
     */
    private String adType;

    /**
     * Database Column Remarks:
     *   广告状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_state
     *
     * @mbg.generated
     */
    private String adState;

    /**
     * Database Column Remarks:
     *   广告创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.ad_add_time
     *
     * @mbg.generated
     */
    private Date adAddTime;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.opr
     *
     * @mbg.generated
     */
    private String opr;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.opr_time
     *
     * @mbg.generated
     */
    private Date oprTime;

    /**
     * Database Column Remarks:
     *   其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.otherother
     *
     * @mbg.generated
     */
    private String otherother;

    /**
     * Database Column Remarks:
     *   其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_info.otherothers
     *
     * @mbg.generated
     */
    private String otherothers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_id
     *
     * @return the value of advertising_info.ad_id
     *
     * @mbg.generated
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_id
     *
     * @param adId the value for advertising_info.ad_id
     *
     * @mbg.generated
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_title
     *
     * @return the value of advertising_info.ad_title
     *
     * @mbg.generated
     */
    public String getAdTitle() {
        return adTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_title
     *
     * @param adTitle the value for advertising_info.ad_title
     *
     * @mbg.generated
     */
    public void setAdTitle(String adTitle) {
        this.adTitle = adTitle == null ? null : adTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_url
     *
     * @return the value of advertising_info.ad_url
     *
     * @mbg.generated
     */
    public String getAdUrl() {
        return adUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_url
     *
     * @param adUrl the value for advertising_info.ad_url
     *
     * @mbg.generated
     */
    public void setAdUrl(String adUrl) {
        this.adUrl = adUrl == null ? null : adUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_start
     *
     * @return the value of advertising_info.ad_start
     *
     * @mbg.generated
     */
    public String getAdStart() {
        return adStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_start
     *
     * @param adStart the value for advertising_info.ad_start
     *
     * @mbg.generated
     */
    public void setAdStart(String adStart) {
        this.adStart = adStart == null ? null : adStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_end
     *
     * @return the value of advertising_info.ad_end
     *
     * @mbg.generated
     */
    public String getAdEnd() {
        return adEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_end
     *
     * @param adEnd the value for advertising_info.ad_end
     *
     * @mbg.generated
     */
    public void setAdEnd(String adEnd) {
        this.adEnd = adEnd == null ? null : adEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_sort
     *
     * @return the value of advertising_info.ad_sort
     *
     * @mbg.generated
     */
    public String getAdSort() {
        return adSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_sort
     *
     * @param adSort the value for advertising_info.ad_sort
     *
     * @mbg.generated
     */
    public void setAdSort(String adSort) {
        this.adSort = adSort == null ? null : adSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_click
     *
     * @return the value of advertising_info.ad_click
     *
     * @mbg.generated
     */
    public String getAdClick() {
        return adClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_click
     *
     * @param adClick the value for advertising_info.ad_click
     *
     * @mbg.generated
     */
    public void setAdClick(String adClick) {
        this.adClick = adClick == null ? null : adClick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_type
     *
     * @return the value of advertising_info.ad_type
     *
     * @mbg.generated
     */
    public String getAdType() {
        return adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_type
     *
     * @param adType the value for advertising_info.ad_type
     *
     * @mbg.generated
     */
    public void setAdType(String adType) {
        this.adType = adType == null ? null : adType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_state
     *
     * @return the value of advertising_info.ad_state
     *
     * @mbg.generated
     */
    public String getAdState() {
        return adState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_state
     *
     * @param adState the value for advertising_info.ad_state
     *
     * @mbg.generated
     */
    public void setAdState(String adState) {
        this.adState = adState == null ? null : adState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.ad_add_time
     *
     * @return the value of advertising_info.ad_add_time
     *
     * @mbg.generated
     */
    public Date getAdAddTime() {
        return adAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.ad_add_time
     *
     * @param adAddTime the value for advertising_info.ad_add_time
     *
     * @mbg.generated
     */
    public void setAdAddTime(Date adAddTime) {
        this.adAddTime = adAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.opr
     *
     * @return the value of advertising_info.opr
     *
     * @mbg.generated
     */
    public String getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.opr
     *
     * @param opr the value for advertising_info.opr
     *
     * @mbg.generated
     */
    public void setOpr(String opr) {
        this.opr = opr == null ? null : opr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.opr_time
     *
     * @return the value of advertising_info.opr_time
     *
     * @mbg.generated
     */
    public Date getOprTime() {
        return oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.opr_time
     *
     * @param oprTime the value for advertising_info.opr_time
     *
     * @mbg.generated
     */
    public void setOprTime(Date oprTime) {
        this.oprTime = oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.otherother
     *
     * @return the value of advertising_info.otherother
     *
     * @mbg.generated
     */
    public String getOtherother() {
        return otherother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.otherother
     *
     * @param otherother the value for advertising_info.otherother
     *
     * @mbg.generated
     */
    public void setOtherother(String otherother) {
        this.otherother = otherother == null ? null : otherother.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_info.otherothers
     *
     * @return the value of advertising_info.otherothers
     *
     * @mbg.generated
     */
    public String getOtherothers() {
        return otherothers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_info.otherothers
     *
     * @param otherothers the value for advertising_info.otherothers
     *
     * @mbg.generated
     */
    public void setOtherothers(String otherothers) {
        this.otherothers = otherothers == null ? null : otherothers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adId=").append(adId);
        sb.append(", adTitle=").append(adTitle);
        sb.append(", adUrl=").append(adUrl);
        sb.append(", adStart=").append(adStart);
        sb.append(", adEnd=").append(adEnd);
        sb.append(", adSort=").append(adSort);
        sb.append(", adClick=").append(adClick);
        sb.append(", adType=").append(adType);
        sb.append(", adState=").append(adState);
        sb.append(", adAddTime=").append(adAddTime);
        sb.append(", opr=").append(opr);
        sb.append(", oprTime=").append(oprTime);
        sb.append(", otherother=").append(otherother);
        sb.append(", otherothers=").append(otherothers);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}