package com.example.torder.domain;

import com.cetccity.common.base.com.cetccity.torder.domain.BasePo;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table log_info
 */
public class Log extends BasePo implements Serializable {
    /**
     * Database Column Remarks:
     *   日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.log_id
     *
     * @mbg.generated
     */
    private Integer logId;

    /**
     * Database Column Remarks:
     *   操作用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.operate_time
     *
     * @mbg.generated
     */
    private Date operateTime;

    /**
     * Database Column Remarks:
     *   ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   链接路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.operate_url
     *
     * @mbg.generated
     */
    private String operateUrl;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.opr
     *
     * @mbg.generated
     */
    private Integer opr;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.opr_time
     *
     * @mbg.generated
     */
    private Date oprTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.log_id
     *
     * @return the value of log_info.log_id
     *
     * @mbg.generated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.log_id
     *
     * @param logId the value for log_info.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.user_id
     *
     * @return the value of log_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.user_id
     *
     * @param userId the value for log_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.operate_time
     *
     * @return the value of log_info.operate_time
     *
     * @mbg.generated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.operate_time
     *
     * @param operateTime the value for log_info.operate_time
     *
     * @mbg.generated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.ip
     *
     * @return the value of log_info.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.ip
     *
     * @param ip the value for log_info.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.operate_url
     *
     * @return the value of log_info.operate_url
     *
     * @mbg.generated
     */
    public String getOperateUrl() {
        return operateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.operate_url
     *
     * @param operateUrl the value for log_info.operate_url
     *
     * @mbg.generated
     */
    public void setOperateUrl(String operateUrl) {
        this.operateUrl = operateUrl == null ? null : operateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.opr
     *
     * @return the value of log_info.opr
     *
     * @mbg.generated
     */
    public Integer getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.opr
     *
     * @param opr the value for log_info.opr
     *
     * @mbg.generated
     */
    public void setOpr(Integer opr) {
        this.opr = opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.opr_time
     *
     * @return the value of log_info.opr_time
     *
     * @mbg.generated
     */
    public Date getOprTime() {
        return oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.opr_time
     *
     * @param oprTime the value for log_info.opr_time
     *
     * @mbg.generated
     */
    public void setOprTime(Date oprTime) {
        this.oprTime = oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", userId=").append(userId);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", ip=").append(ip);
        sb.append(", operateUrl=").append(operateUrl);
        sb.append(", opr=").append(opr);
        sb.append(", oprTime=").append(oprTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}