package com.example.torder.domain;

import com.cetccity.common.base.com.cetccity.torder.domain.BasePo;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table menu_info
 */
public class Menu extends BasePo implements Serializable {
    /**
     * Database Column Remarks:
     *   菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_id
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     * Database Column Remarks:
     *   上级菜单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_parent_id
     *
     * @mbg.generated
     */
    private Integer menuParentId;

    /**
     * Database Column Remarks:
     *   菜单路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_url
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     * Database Column Remarks:
     *   菜单类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_type
     *
     * @mbg.generated
     */
    private Integer menuType;

    /**
     * Database Column Remarks:
     *   菜单排序码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_sort
     *
     * @mbg.generated
     */
    private Integer menuSort;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.opr
     *
     * @mbg.generated
     */
    private String opr;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.opr_time
     *
     * @mbg.generated
     */
    private Date oprTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.other
     *
     * @mbg.generated
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_id
     *
     * @return the value of menu_info.menu_id
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_id
     *
     * @param menuId the value for menu_info.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_name
     *
     * @return the value of menu_info.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_name
     *
     * @param menuName the value for menu_info.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_parent_id
     *
     * @return the value of menu_info.menu_parent_id
     *
     * @mbg.generated
     */
    public Integer getMenuParentId() {
        return menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_parent_id
     *
     * @param menuParentId the value for menu_info.menu_parent_id
     *
     * @mbg.generated
     */
    public void setMenuParentId(Integer menuParentId) {
        this.menuParentId = menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_url
     *
     * @return the value of menu_info.menu_url
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_url
     *
     * @param menuUrl the value for menu_info.menu_url
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_type
     *
     * @return the value of menu_info.menu_type
     *
     * @mbg.generated
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_type
     *
     * @param menuType the value for menu_info.menu_type
     *
     * @mbg.generated
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_sort
     *
     * @return the value of menu_info.menu_sort
     *
     * @mbg.generated
     */
    public Integer getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_sort
     *
     * @param menuSort the value for menu_info.menu_sort
     *
     * @mbg.generated
     */
    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.opr
     *
     * @return the value of menu_info.opr
     *
     * @mbg.generated
     */
    public String getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.opr
     *
     * @param opr the value for menu_info.opr
     *
     * @mbg.generated
     */
    public void setOpr(String opr) {
        this.opr = opr == null ? null : opr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.opr_time
     *
     * @return the value of menu_info.opr_time
     *
     * @mbg.generated
     */
    public Date getOprTime() {
        return oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.opr_time
     *
     * @param oprTime the value for menu_info.opr_time
     *
     * @mbg.generated
     */
    public void setOprTime(Date oprTime) {
        this.oprTime = oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.other
     *
     * @return the value of menu_info.other
     *
     * @mbg.generated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.other
     *
     * @param other the value for menu_info.other
     *
     * @mbg.generated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuParentId=").append(menuParentId);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append(", menuType=").append(menuType);
        sb.append(", menuSort=").append(menuSort);
        sb.append(", opr=").append(opr);
        sb.append(", oprTime=").append(oprTime);
        sb.append(", other=").append(other);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}