package com.example.torder.domain;

import com.cetccity.common.base.domain.BasePo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_right
 */
public class RoleRight extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right.rr_id
     *
     * @mbg.generated
     */
    private Integer rrId;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right.rr_role_id
     *
     * @mbg.generated
     */
    private Integer rrRoleId;

    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right.rr_right_id
     *
     * @mbg.generated
     */
    private Integer rrRightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right.opr
     *
     * @mbg.generated
     */
    private Integer opr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right.oprtime
     *
     * @mbg.generated
     */
    private Date oprtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_right
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right.rr_id
     *
     * @return the value of role_right.rr_id
     *
     * @mbg.generated
     */
    public Integer getRrId() {
        return rrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right.rr_id
     *
     * @param rrId the value for role_right.rr_id
     *
     * @mbg.generated
     */
    public void setRrId(Integer rrId) {
        this.rrId = rrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right.rr_role_id
     *
     * @return the value of role_right.rr_role_id
     *
     * @mbg.generated
     */
    public Integer getRrRoleId() {
        return rrRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right.rr_role_id
     *
     * @param rrRoleId the value for role_right.rr_role_id
     *
     * @mbg.generated
     */
    public void setRrRoleId(Integer rrRoleId) {
        this.rrRoleId = rrRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right.rr_right_id
     *
     * @return the value of role_right.rr_right_id
     *
     * @mbg.generated
     */
    public Integer getRrRightId() {
        return rrRightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right.rr_right_id
     *
     * @param rrRightId the value for role_right.rr_right_id
     *
     * @mbg.generated
     */
    public void setRrRightId(Integer rrRightId) {
        this.rrRightId = rrRightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right.opr
     *
     * @return the value of role_right.opr
     *
     * @mbg.generated
     */
    public Integer getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right.opr
     *
     * @param opr the value for role_right.opr
     *
     * @mbg.generated
     */
    public void setOpr(Integer opr) {
        this.opr = opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right.oprtime
     *
     * @return the value of role_right.oprtime
     *
     * @mbg.generated
     */
    public Date getOprtime() {
        return oprtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right.oprtime
     *
     * @param oprtime the value for role_right.oprtime
     *
     * @mbg.generated
     */
    public void setOprtime(Date oprtime) {
        this.oprtime = oprtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rrId=").append(rrId);
        sb.append(", rrRoleId=").append(rrRoleId);
        sb.append(", rrRightId=").append(rrRightId);
        sb.append(", opr=").append(opr);
        sb.append(", oprtime=").append(oprtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}